# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve -l -H localhost`. If you change this file, please restart the 
# server process.

# Basic Site Settings
locale                   : "en-US"
site_theme               : "default" # Currently available options are "default", "air"
title                    : "Yutong He/Personal Homepage"
title_separator          : "-"
name                     : &name "Yutong He"
description              : &description "Yutong He's academic portfolio"   # Update this with a general description of your site, this is the default if not overridden by a page
url                      : https://ytonghe.github.io # The base hostname & protocol for your site e.g. "https://[your GitHub username].github.io",
                                                           # or if you already have some other page hosted on Github then use "https://[your GitHub username].github.io/[Your Repo Name]"
baseurl                  : "" # the subpath of your site, e.g. "/blog"
repository               : "ytonghe/ytonghe.github.io"

# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author:
  # Biographic information
  avatar           : "heyutong.png"
  name             : "Yutong He(贺雨彤)"
  bio              : "Hunan University Of Technology and Business"
  email            : "heyutong0220@163.com" 
  location         : "China Hunan"
  # Academic websites
  academia         : # URL
  arxiv            : # URL - Update with the correct link to your profile
  googlescholar    : #"https://scholar.google.com/citations?user=PS_CX0AAAAAJ"
  inspire-hep      : # URL
  impactstory      : # URL
  orcid            : #"https://orcid.org/yourorcidurl"
  semantic         : # URL
  pubmed           : #"https://www.ncbi.nlm.nih.gov/pubmed/?term=john+snow"
  researchgate     : # URL
  scopus           : # URL

  # Repositories and software development
  bitbucket        : # Username - Update with your username on the site
  codepen          : # Username
  dribbble         : # Username
  github           : "https://github.com/ytonghe"
  kaggle           : # Username  
  stackoverflow    : # User number or user number and name (i.e., use "1" or "1/jeff-atwood")    

  # Social media
  artstation       : # Username
  bluesky          : #"bsky.app" # Replace this with you Bluesky username
  facebook         : # Username
  flickr           : # Username
  foursquare       : # Username
  goodreads        : # Username
  google_plus      : # Username
  keybase          : # Username
  instagram        : # Username
  lastfm           : # Username
  linkedin         : # Username
  mastodon         : # URL
  medium           : # URL
  pinterest        : # Username
  soundcloud       : # Username
  steam            : # Username
  telegram         : # URL
  tumblr           : # Username
  twitter          : # Username for X / Twitter
  vine             : # Username
  weibo            : # Username
  wikipedia        : # Username
  xing             : # Username
  youtube          : # Username
  zhihu            : # Username
